### ISSUE TITLE
UnicodeDecodeError: invalid start byte with Starlette & Mangum

### ISSUE THREAD

**Issue by erichaus** [fullonic/brotli-asgi#12]
Hello,

Getting the following error when using brotli-asgi with Starlette & [Mangum](https://github.com/jordaneremieff/mangum)

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1: invalid start byte`

This error looks similar to a past issue over in Mangum regarding Gzip support: https://github.com/jordaneremieff/mangum/issues/90

**Comment by fullonic** [comment]
hey @burritoIand! Thanks for sharing the error. I never used Mangum, but after reading the issue you mentioned  (https://github.com/jordaneremieff/mangum/issues/90) and the PR that solved it, looks like the problem is related with Mangum. Let's keep this issue open until the problem is fixed. I will keep an eye on your ticket https://github.com/jordaneremieff/mangum/issues/139

**Comment by fullonic** [comment]
This is issue was already solved by PR https://github.com/jordaneremieff/mangum/pull/140.
